version: "3.5"

services:
  postgres:
    container_name: $CONTAINER_NAME
    image: postgis/postgis:17-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: heslo
      PGDATA: /data/postgres
    volumes:
      - ${HOME_DIR}/PG_Data:/data/postgres
      - ${HOME_DIR}:/home
    ports:
      - "5432:5432"
    command:
      [
        "postgres",
        "-c",
        "logging_collector=on",
        "-c",
        "log_statement=all",
        "-c",
        "log_directory=/tmp",
      ]
