version: '3.5'

services:
  postgres:
    container_name: $CONTAINER_NAME
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
       - ${HOME_DIR}/PG_Data:/data/postgres
    ports:
      - "5430:5432"

