R_LIBS_USER=$HOME/R

QGIS_SOURCES_DIR=$HOME/QGIS
QGIS_BUILD_DIR=$QGIS_SOURCES_DIR/build-qt

DIR_CODES=$HOME/Codes
DIR_WORK=
DIR_QGIS_PROFILES=$HOME/.local/share/QGIS/QGIS3:/root/.local/share/QGIS/QGIS3

KEYS_FOLDER=/usr/share/keyrings
SOURCES_FOLDER=/etc/apt/sources.list.d

BACKUP_DIR_PROFILE=$HOME/_backup/

PYTHONNOUSERSITE=True

PYTHON_ENVS_DIR=/opt/python_envs
MAIN_ENV=global-env
MAIN_ENV_ACTIVATE=$PYTHON_ENVS_DIR/$MAIN_ENV/bin/activate

PATH=$PATH:$HOME/.cargo/bin
PATH=$PATH:$HOME/bin:/usr/local/texlive/2024/bin/x86_64-linux
PATH=$PATH:$HOME/.local/bin
#PATH=$PATH:$HOME/miniconda3/bin

SCRIPTS_DIR=$HOME/Scripts

PATH=$PATH:$SCRIPTS_DIR
PATH=$PATH:$SCRIPTS_DIR/tools
PATH=$PATH:$SCRIPTS_DIR/python_programs
PATH=$PATH:$SCRIPTS_DIR/qgis
PATH=$PATH:$SCRIPTS_DIR/docker_run

VariablesFile=$HOME/.install_env_variables

QGIS_WORKTREE_FOLDER="/QGIS"

# TODO FILL
PGHOST=localhost
PGPORT=5432
PGUSER=
PGPASSWORD=
