install.packages(c(
    "tidyverse", 
    "tidymodels",
    "tidyclust",
    "here",
    "shiny",
    "terra", 
    "sf", 
    "sabre",
    "SpatialKDE",
    "devtools",
    "remotes",
    "easystats"
    ),
    lib=Sys.getenv("R_LIBS_USER")
)