name: Test scripts

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on: [push]

jobs:

  test-scripts:

    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run first_run.sh
        run: ./first_run.sh
      
      - name: Run complete_install.sh
        shell: zsh {0}
        run: ./complete_install.sh
