name: Test scripts - Debian

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - first_run.sh
      - complete_install.sh
      - "install/**"
      - "python_programs/**"
      - ".github/workflows/test-questing.yml"

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  test-scripts:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        container: [debian:trixie, debian:testing]

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Setup
        run: |
          apt-get update
          apt-get install -y sudo git

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run first_run.sh
        run: ./first_run.sh

      - name: Run complete_install.sh
        shell: zsh {0}
        run: ./complete_install.sh
