name: Test scripts

on: [push]

jobs:

  test-scripts:

    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run first_run.sh
        run: ./first_run.sh
      
      - name: Runc complete_install.sh
        run: ./complete_install.sh
