name: Test scripts

on: [push]

jobs:

  test-scripts:

    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Echo HOME
        run: echo $HOME

      - name: List files in repository
        run: ls -la

      - name: Run first_run.sh
        run: ./first_run.sh
